package cluster

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	machineapi "github.com/siderolabs/talos/pkg/machinery/api/machine"
)

// RECONFIGURE IS THE ONLY WRITE PATH TO A MACHINE THAT ALREADY EXISTS.
//
// Up is bootstrap: every step describes a node being brought into being, and it
// SKIPS config generation entirely once a talosconfig is in the state dir —
// deliberately, because regenerating there would mint a fresh secrets bundle and
// take away the only credential that reaches the node. The cost of that skip is
// that a manifest edit had nowhere to go. Adding a registry mirror to an adopted
// node meant wiping the disk and starting over.
//
// This file closes that gap and nothing else. It does not create machines, it
// does not boot them, and it refuses anything that a running node cannot be
// talked into — see reconfigureRefusals below, which is most of the value here.

// ReconfigureOptions is what regenerating a config for an existing machine
// needs. Every field is the same value Up was given, because the config is
// regenerated by the SAME generator: a second one would drift, and the drift
// would land on a node's disk.
type ReconfigureOptions struct {
	ClusterName string
	StateDir    string
	// TalosEndpoint is the authenticated API, host:port. For an adopted node
	// this is the address it answers on AFTER the install, never the
	// maintenance endpoint — a machine that can be reconfigured is by
	// definition one that left maintenance mode.
	TalosEndpoint string
	KubeEndpoint  string
	APIAddress    string

	SystemDisk       DiskRef
	DataDiskSerial   string
	EphemeralMaxSize string
	ConsoleArg       string
	DisableKexec     bool
	Network          *Network
	Registries       []RegistryMirror
	ConfigPatches    []string
}

// Reconfigure regenerates this machine's config from its manifest and applies
// it to the running node.
//
// The node's Talos version is asked of the NODE rather than taken from a
// manifest or an image: the machine is running, so it is the authority on what
// it is, and the installer pin written into the new config must not silently
// become a cross-version upgrade.
//
// Returns the applied config so callers can report on it. It contains the
// cluster's certificate authorities and is SECRET.
func Reconfigure(ctx context.Context, opts ReconfigureOptions) ([]byte, error) {
	talosconfig, configured, err := ReadTalosconfig(opts.StateDir)
	if err != nil {
		return nil, err
	}

	// NOTHING TO RECONFIGURE. A machine with no talosconfig has never been
	// brought up, and pointing this at it would generate a first config
	// out of band — with no install, no bootstrap, and a state dir that then
	// claims a node exists.
	if !configured {
		return nil, fmt.Errorf("this machine has no talosconfig in %s, so it has never been "+
			"brought up and there is no running node to reconfigure\n\n"+
			"  use `tinq up` for a VM, or `tinq adopt` for hardware", opts.StateDir)
	}

	// SECRET, and the reason this whole path exists. Regenerating without it
	// mints five new certificate authorities and a new machine token: the node
	// rejects the config as signed by a CA it does not trust, and nothing in
	// the state dir can reach it afterwards.
	secretsBundle, err := os.ReadFile(filepath.Join(opts.StateDir, "secrets.yaml"))
	if err != nil {
		return nil, fmt.Errorf("reading this machine's secrets bundle: %w\n\n"+
			"  it is what keeps the regenerated config trusted by a node that is already "+
			"running. Without it a new config cannot be generated for THIS machine, only "+
			"for a different one", err)
	}

	version, err := InstalledNodeVersion(ctx, talosconfig, opts.TalosEndpoint, NodeVersionTimeout)
	if err != nil {
		return nil, err
	}

	generated, err := GenerateConfig(ConfigInput{
		ClusterName:      opts.ClusterName,
		Endpoint:         opts.KubeEndpoint,
		APIAddress:       opts.APIAddress,
		TalosVersion:     version,
		ConsoleArg:       opts.ConsoleArg,
		SystemDisk:       opts.SystemDisk,
		DataDiskSerial:   opts.DataDiskSerial,
		EphemeralMaxSize: opts.EphemeralMaxSize,
		DisableKexec:     opts.DisableKexec,
		Network:          opts.Network,
		Registries:       opts.Registries,
		ConfigPatches:    opts.ConfigPatches,
		SecretsBundle:    secretsBundle,
	})
	if err != nil {
		return nil, err
	}

	current, err := os.ReadFile(filepath.Join(opts.StateDir, "controlplane.yaml"))
	if err != nil {
		return nil, fmt.Errorf("reading this machine's current config: %w", err)
	}

	if err := reconfigureRefusals(current, generated.ControlPlane); err != nil {
		return nil, err
	}

	// BEFORE the apply, not after. An apply is not free — AUTO mode may decide
	// an identical config still warrants restarting a service — and a verb that
	// reboots a healthy node for a no-op change is one nobody runs twice.
	if unchanged(current, generated.ControlPlane) {
		return nil, errNothingToApply
	}

	// APPLIED BEFORE IT IS WRITTEN, which is the opposite order from Up's.
	// Up writes first because a failed apply leaves artifacts that explain why,
	// against a machine that does not exist yet. Here the machine DOES exist
	// and the file on disk is the record of what it is running: overwriting it
	// with a config the node rejected would make the state dir lie about a live
	// machine.
	if err := applyToRunningNode(ctx, talosconfig, opts.TalosEndpoint, generated.ControlPlane); err != nil {
		return nil, err
	}

	// controlplane.yaml ONLY. talosconfig and secrets.yaml are deliberately not
	// rewritten: the bundle is unchanged by construction, and the talosconfig
	// carries a freshly minted client certificate that is valid but pointless
	// to swap in. Rewriting the one credential that reaches this node, at the
	// end of an operation that just changed the node, adds a way to lose it.
	if err := writeArtifacts(opts.StateDir, map[string][]byte{
		"controlplane.yaml": generated.ControlPlane,
	}); err != nil {
		return nil, err
	}

	return generated.ControlPlane, nil
}

// applyToRunningNode applies a config over the AUTHENTICATED API.
//
// Mode AUTO, not REBOOT: Talos decides whether what changed needs one, so a
// registry mirror lands without an outage and something structural still gets
// the reboot it requires. REBOOT here would restart the node for every edit,
// and NO_REBOOT would silently drop changes that cannot apply live.
//
// The config is SECRET (five certificate authorities and the machine token) and
// is never logged; the node's own error is about fields and is wrapped normally.
func applyToRunningNode(ctx context.Context, talosconfig []byte, endpoint string, config []byte) error {
	c, err := AuthenticatedClient(ctx, talosconfig, endpoint)
	if err != nil {
		return err
	}

	defer c.Close() //nolint:errcheck

	if _, err := c.ApplyConfiguration(ctx, &machineapi.ApplyConfigurationRequest{
		Data: config,
		Mode: machineapi.ApplyConfigurationRequest_AUTO,
	}); err != nil {
		return fmt.Errorf("applying the machine config: %w", err)
	}

	return nil
}

// installDiskSelector matches the install block's disk selector — the whole
// block, whichever identity it names. The PAIRING is the point: `serial:`
// anywhere in a config proves nothing about which disk Talos installs to.
var installSelectorBlock = regexp.MustCompile(`(?m)^ {8}diskSelector:\n((?: {12}\S+: .*\n)+)`)

// volumeKinds are the config documents that describe PARTITIONS. Both are
// compared WHOLE rather than field by field, because every field in them is
// install-time and a per-field list is a list that will one day be missing the
// field that mattered — machinery adds one, the comparison keeps passing, and
// the state dir starts describing a disk that does not exist.
//
// `what` is the OPERATOR's name for it and `kind` is Talos's. The refusal leads
// with the operator's, because the person reading it edited a manifest field
// and has no reason to know which config document that became.
var volumeKinds = []struct{ kind, what, field string }{
	{"VolumeConfig", "the EPHEMERAL cap", "spec.baremetal.ephemeralMaxSize"},
	{"UserVolumeConfig", "the user volume's disk", "spec.dataDisk / spec.baremetal.dataDiskSerial"},
}

// splitDocs splits a rendered config into its YAML documents.
//
// The separator is a line that is exactly `---`. Machinery's encoder emits
// exactly that between documents, and requiring the whole line keeps a `---`
// inside a value from splitting one document into two.
func splitDocs(b []byte) []string {
	return strings.Split(string(b), "\n---\n")
}

// docOfKind returns the document declaring `kind`, and whether there was one.
func docOfKind(b []byte, kind string) (string, bool) {
	for _, doc := range splitDocs(b) {
		if strings.Contains(doc, "\nkind: "+kind+"\n") || strings.HasPrefix(doc, "kind: "+kind+"\n") {
			return doc, true
		}
	}

	return "", false
}

// reconfigureRefusals compares the running config with the regenerated one and
// refuses the changes a running node cannot honour.
//
// IT REFUSES RATHER THAN WARNS. A warning about a partition layout scrolls past
// in a transcript, and what follows it is a cluster that looks configured and is
// not. Talos accepts a config naming a different install disk or EPHEMERAL cap
// and does NOTHING about it — the partitions are already written — so there is
// no failure downstream to catch this later.
func reconfigureRefusals(current, next []byte) error {
	var changed []string

	if was, now := installSelectorBlock.FindStringSubmatch(string(current)),
		installSelectorBlock.FindStringSubmatch(string(next)); !sameSubmatch(was, now) {
		changed = append(changed, fmt.Sprintf("  the install disk (spec.baremetal.systemDiskSerial / systemDiskWWID):\n%s    -> \n%s",
			indentOrNone(was), indentOrNone(now)))
	}

	for _, v := range volumeKinds {
		was, hadIt := docOfKind(current, v.kind)
		now, hasIt := docOfKind(next, v.kind)

		switch {
		case !hadIt && !hasIt:
			continue
		case hadIt != hasIt:
			verb := "added"
			if hadIt {
				verb = "removed"
			}

			changed = append(changed, fmt.Sprintf("  %s (%s) is being %s — the %s document",
				v.what, v.field, verb, v.kind))
		case strings.TrimSpace(was) != strings.TrimSpace(now):
			changed = append(changed, fmt.Sprintf("  %s (%s) has changed — the %s document",
				v.what, v.field, v.kind))
		}
	}

	if len(changed) == 0 {
		return nil
	}

	return fmt.Errorf("this change is decided when the disk is PARTITIONED, and this machine's "+
		"disk is already partitioned:\n\n%s\n\n"+
		"  Talos accepts a config saying otherwise and does nothing about it, so the state dir\n"+
		"  would describe a layout the disk does not have. The first sign is a PVC that never\n"+
		"  binds, or an install target that names nothing.\n\n"+
		"  to change these, wipe the machine and bring it up again", strings.Join(changed, "\n"))
}

func sameSubmatch(a, b []string) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}

	return strings.TrimSpace(a[1]) == strings.TrimSpace(b[1])
}

func indentOrNone(m []string) string {
	if m == nil {
		return "    (none)\n"
	}

	return m[1]
}

// unchanged reports whether two rendered configs are the same document.
//
// Exported nowhere and used by the CLI only to say "nothing to do" rather than
// applying a config identical to the running one — an apply is not free, and
// AUTO mode may decide an identical config still warrants a restart.
func unchanged(current, next []byte) bool {
	return bytes.Equal(current, next)
}

var errNothingToApply = errors.New("the regenerated config is identical to the one this machine is running")

// InstalledEndpoint is installedEndpoint, exported for cmd/tinq.
//
// Reconfigure needs the address a node answers on AFTER its install for the
// same reason Up does, and deriving it a second time in package main is how the
// two would come to disagree about a re-pinned node.
func InstalledEndpoint(endpoint string, n *Network) (addr, hostPort string, err error) {
	return installedEndpoint(endpoint, n)
}

// APIAddressOf is apiAddress, exported for cmd/tinq. Same reasoning: the
// certificate must name what the client dials, and one derivation is what keeps
// that true.
func APIAddressOf(endpoint string) (string, error) {
	return apiAddress(endpoint)
}

// ErrNothingToApply reports a manifest that already matches the running node.
// It is a SUCCESS for callers that re-run, which is why it is exported rather
// than rendered as a failure.
var ErrNothingToApply = errNothingToApply
